### ISSUE TITLE
Openelec compatible ?

### ISSUE THREAD

**Issue by TechaY** [RanzQ/hyperion-audio-effects#10]
Hello,

I would like to know if i can install hyperion audio-effects on openelec ? 
I 've got Raspberry Pi 2 with Rasplex and Hyperion on it. It could be nice if i could use Rasplex with it. 

Thank's.

**Comment by RanzQ** [comment]
I'm not sure how you would install gstreamer 1.0 on Openelec. That's basically the only dependency. It was discussed (https://github.com/RanzQ/hyperion-audio-effects/issues/9#issuecomment-114895214)[here] that it's possible to run this on Pi but the performance should be improved a lot for it to be useful. The VU meter effect isn't that heavy but I doubt it would be fast enough.

**Comment by TylonHH** [comment]
@TechaY Did you tried it?

**Comment by RanzQ** [comment]
@TylonHH I added instructions for OSMC, check readme. I might try OpenELEC too but it might be more complex to setup.

**Comment by TylonHH** [comment]
Openelec doesn't support 'apt-get'.

**Comment by RanzQ** [comment]
TylonHH, yes most of the stuff must be manually compiled. :)

**Comment by lstegger** [comment]
@RanzQ Hey RanzQ,
I'm following this repo for a while now and I would love to check this on my Raspberry Pi 2 using LibreELEC. Any chance you could try that some day? I don't think I could manage to compile the dependencies manually without clear instructions.
It becomes very interesting again in my opinion as Spotify Connect is now supported by LibreELEC (cf. https://forum.libreelec.tv/thread-1206.html). 
I appreciate any help! Thanks a lot!

**Comment by RanzQ** [comment]
@lstegger It seems to be based on this: https://github.com/Fornoth/spotify-connect-web which works on any RPi2. My kit works on any debian based distro, like OSMC. Instructions: https://discourse.osmc.tv/t/howto-setup-a-spotify-connect-web-server-on-a-raspberry-pi-with-osmc/15818

I might try some some day to build this into a package for LibreELEC. That would require some help from LibreELEC team though.

**Comment by lstegger** [comment]
@RanzQ thanks for your quick reply. I preferred LibreELEC over OSMC as it seemed to have a better performance. But maybe I'll give it a try, thanks for the instructions! 👍 A LibreELEC package would be awesome, if you find time and people to do it some day :)

**Comment by RanzQ** [comment]
@lstegger All the packages are built especially for LibreELEC, that's why it's fast. Adding a simple library wouldn't be so hard but for now this package requires gstreamer and python, which are quite complex.

**Comment by RanzQ** [comment]
Closing this for now since I don't have interest in OpenELEC myself.
