### ISSUE TITLE
How to get this effect?

### ISSUE THREAD

**Issue by behtjes** [RanzQ/hyperion-audio-effects#20]
I've seen your effect on youtube, but this isn't the color spectrum right?

https://www.youtube.com/watch?v=HiAlv-mW9UI

How to get this effect?

**Comment by behtjes** [comment]
bump :)

**Comment by RanzQ** [comment]
Sorry, forgot to answer. :) It is `color_spectrum` but an earlier version. I've changed the implementation quite a lot. The settings `mirror` makes 2 identical sides. The setting `color-speed` should enable changing colors but it's not currently implemented. I'll check [this TODO](https://github.com/RanzQ/hyperion-audio-effects/blob/master/effects/color_spectrum.py#L198) at some point if it's doable.

**Comment by behtjes** [comment]
Ok nice. Thanks for the answer. It would be nice to be able to change colors,  or chose the amount of colors/octaves that will be used.

**Comment by RanzQ** [comment]
Video of the changing color and limited hue: https://www.youtube.com/watch?v=AOv9BwbtA6w

**Comment by behtjes** [comment]
Very nice! I'll try it asap

**Comment by RanzQ** [comment]
@behtjes also the effect is nicer if you use `"band-width-exp": 2`, but takes some processing power, not suitable for rpi. :P

**Comment by behtjes** [comment]
OK. What's the max bandwidth for the pi3?

**Comment by RanzQ** [comment]
Haven't tried, but I guess 4-5. Run it and check with `top` how much CPU it uses.
