### ISSUE TITLE
green-yellow-reds are shining when room is silent

### ISSUE THREAD

**Issue by pete111** [RanzQ/hyperion-audio-effects#24]
Hi RanzQ, first of all - Thank you for your pretty awesome audio visualizer!
But I have this "problem".  With color_spectrum effect the last leds on my LED strip are always shining green to red (when music is playing as well as music is off - see picture).
With vumeter effect it is similar (but without reds, these are shining when music is playing, but I have always on yellow up to green leds).

I found out, when I adjust level-min and magnitude-min (higher than 0), it turns these green leds off, but they are usually at 99% not shining (maybe basses/beats).

P.S. No idea why in silent room even green-yellow-red leds are always on even when no music is playing (silent room) - when setting value for level-min/magnitude-min is zero. Many thanks

**Comment by RanzQ** [comment]
What kind of hardware? And you forgot to post the picture?

**Comment by pete111** [comment]
Hello RanzQ, sorry, I forgot to post picture - posting now [image](https://preview.ibb.co/dCbbkk/20170415_163745.jpg). This is how it looks like while silent room, red leds are on strip end, green leds - strip "start" and before green are many leds turned off which is ok, but I think green-red leds should be turned off as well while silence. 
I found out, when I experiment with magnitude-min, then I am able to "leave off" there green-red part leds too, but then it reacts to sound from higher volume. I made microphone myself for orangepi.

**Comment by RanzQ** [comment]
It's been a while, forgot to answer this. I didn't fully understand your problem. One thing I know for sure is that you need to manually adjust the volume in the software playing the audio since there's now auto-adjustment. This applies for the loopback case. For microphone one should adjust the input level. Reopen if you still need help with this. :)
